import React, { ReactNode } from 'react'
import '@/app/globals.css'
import { Navigation } from '@/components/navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-row bg-zinc-700 text-zinc-200">
        <Navigation />
        <div className="flex items-center justify-center w-screen ">
          {children}
        </div>
      </body>
    </html>
  )
}
